site_name:           Michigan Autonomous Vehicles (MAVs)
repo_url:            https://github.com/JuliaMPC/AVExamples.jl
site_description:    This is the documentation for MAVs
site_author:         Huckleberry Febbo
theme:               readthedocs

markdown_extensions:
  - codehilite
  - extra
  - tables
  - fenced_code
  - mdx_math # For LaTeX

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

docs_dir: 'build'

pages:
- Introduction: index.md
